### ISSUE TITLE
Table doesn't grow/shrink to accommodate lists of items with variable sizes

### ISSUE THREAD

**Issue by alexkieling** [OfficeDev/Word-Add-in-JavaScript-InvoiceManager#3]
The table population only works because all orders contain exactly 6 items. Try changing the number of items of the sample orders. You will see that the table doesn't adapt to accommodate the items.

**Comment by gbrown31** [comment]
Is there any example available detailing how to accommodate a Custom XML Part that doesn't have a fix number of items? If not, this example is at best misleading.

**Comment by MIchaelMainer** [comment]
@gbrown31 - I agree. We need a better sample than this one. I'll add this to our backlog. Thank you for the feedback.

**Comment by dcu-sharepoint** [comment]
@Michael

We don’t just need you to add it I'll add this to your backlog. We need real and timely solutions and if we need to pay for them, then let us know. But if you are going to provide examples, then make sure they work because sure as hell this one does not.

The problem I'm having with example is that is SOOOO   INCOMPLETEEEEEE. 

Can YOU OR somebody please direct me to a forum or dev center office where I can ask questions.
 
The specific problems I'm having are: 

1)	How to bind the controls in the word document to a SharePoint list. 
2)	How to create a dynamic table control collections so it can be filled from list items.
 
These are critical as I have a customer waiting for a solution and I have not been able to find anything on the subject anywhere! We waste our time showing customer and hoping for the best, but this is ridiculous.
 
And I am sure I am NOT the ONLY ONE!
 
These tutorial create more confusion than the problem they are trying to solve. Look at the comment above, made on October 16, 2016, nearly 4 months ago and no response. What a way to run a business.
 
I demoed this example to one of my customers back in October and it is exactly the solution they need but I have not been able to give the solution to the customer because I can't find any information on how to bind the data from an Office 365 list to a table in a word document. I think the documentation, if written, was probably used as toilet paper BEFORE it was published so the information is in someone's rear end....
 
Sounds rude doesn't it, well the games you twits are playing with us are just as rude if not more so.
 
This is business and we need to treat it as a business NOT A GAME WITH A BACKLOG LIST.

I even called the 800 support but couldn’t get to anyone who can deal with this stuff.

**Comment by Rick-Kirkham** [comment]
@dcu-sharepoint 
Thanks for the suggestion. We'll update the add-in to make it work with more variable data sizes/schemas.

**Comment by alexkieling** [comment]
I can't believe this issue is still open. I'm so glad I don't have to develop Office add-ins anymore.

**Comment by dcu-sharepoint** [comment]
not only is it open, I can't a decent response but instead I get told to got to stackoveflow. if Microsoft doesn't want to answer questions then take the stupid example of GITHUB and be done with it....


there's no docs to be found, they don't know how to respond or guide thru with the so call officedev/js devolpment....


anywho: they closed it and I opened another issue and will continue to open a new issue until they either take it of GITHUB or give a sensible answer other than to go to stackoverflow or HELL for that matter.




________________________________

**Comment by dcu-sharepoint** [comment]
Rick this is not just a SUGGESTION. I need an ANSWER, where can I go to get help.


________________________________

**Comment by Rick-Kirkham** [comment]
I have found another sample that shows table binding with variable data: [Excel-Add-in-Bind-To-Table](https://github.com/OfficeDev/Excel-Add-in-Bind-To-Table). So, it doesn't look like there's much point to updating this sample, so I will close this issue.
