### ISSUE TITLE
How to alter/add/delete the actual word xml parts

### ISSUE THREAD

**Issue by nigel-dewar** [OfficeDev/Word-Add-in-JavaScript-InvoiceManager#5]
This example is missing a HUGE!!!! part for a person to be able to understand.

How does one edit/create/update the xml parts in the word document, and ensure they wire up correctly with the add-in data?

I went into word, enabled the Developer tab, I see nothing useful.
I went to quick parts, I see nothing useful

Why do you guys produce such half ass tutorials so often. The amount of times 
I try to follow along only to find stuff missing, Its so freaking aggravating.

**Comment by dcu-sharepoint** [comment]
and I thought I was the ONLY ONE!

these tutorial create more confusion than the problems they are trying to solve. Look at the comment above, made on October 16, 2016, nearly 4 months ago and no response. what a way to run a business.

I demoed this example to one of my customers back in October and it is exactly the solution they need but I have not been able to give the solution to the customer because I can't find any information on how to bind the data from an Office 365 list to a table in a word document. I think the documentation, if written, was probably used as toilet paper BEFORE it was published so the information is in someone's rear end....

sounds rude doesn't it, well the games you twits are playing with us are just as rude if not more so.

People this is a business and we need to treat it as a business.

**Comment by Rick-Kirkham** [comment]
@nigel-dewar 
I'm sorry no one responded to your issue in October. That should not have happened.
If I understand the issue that you have raised, you are, in effect, requesting a new sample that illustrates "How does one edit/create/update the xml parts in the word document." _I cannot give you a timeline_, but I will investigate whether this sample can be changed to do this without interfering with its basic purpose. Alternatively, perhaps a new sample can be developed that will help. 

In the meantime, please see if [Create better add-ins for Word with Office Open XML](https://dev.office.com/docs/add-ins/word/create-better-add-ins-for-word-with-office-open-xml) answers your question.

Please note that creating an Issue on GitHub is mainly intended as way to report bugs in the sample. To request a new sample or significantly enhanced sample, please use [Office User Voice](https://office.uservoice.com/forums/285186-general). Here's an example: [error-code-message-documentation](https://office.uservoice.com/forums/285186-general/suggestions/9550923-error-code-message-documentation)

**Comment by dcu-sharepoint** [comment]
@nigel-dewar<https://github.com/nigel-dewar>


thank you for your response. the issue I have is that if an example is put in on github for us to work with your technologies then you should be flexible and help when questions are asked. by sending us to another site where they don't know what is going on if EXTREMELY frustrating. I've been very clear on what my needs are and for what I understand others have similar issues with this example therefore IT IS  BUG at least in the documentation and we need for you to fix it or you only fix bad bits and not bad docs....

if we understood or new how to work with the bits we wouldn't be BEGGING for help.

I do thank you for the openXML link which I will study immediately. in the meantime I like to request to ALL of you to review our needs and act accordingly. we are interested in the technology and we would like to help so help us help you and DON'T drives away....

________________________________

**Comment by dcu-sharepoint** [comment]
@nigel-dewar


 To request a new sample or significantly enhanced sample, please use Office User Voice<https://office.uservoice.com/forums/285186-general>.

we're not requesting AN ENHANCED EXAMPLE, what we are requesting is an explanation on how the thing works and how we can customize it.



________________________________
